export type Language = 'he' | 'en'
export const messages = {
  he: {
    brand: 'אלופי הכפל', club: 'מועדון המספרים שלכם', play: 'בואו נשחק', board: 'לוח האלופים', language: 'English',
    eyebrow: 'תרגיל אחד. ניצחון קטן.', title1: 'בדרך לאליפות,', title2: 'כפל אחד בכל פעם.', intro: 'כל לוח הכפל מחכה לכם. מוכנים לאתגר?',
    nameLabel: 'איך קוראים לך?', namePlaceholder: 'השם או הכינוי שלך', nameHint: 'זה השם שיופיע בלוח האלופים. כינוי זה מצוין!', start: 'קדימה, מתחילים!', practice: 'רק לתרגל', practiceMode: 'מצב תרגול', competition: 'משחק תחרות',
    ready: 'מוכנים, היכון… כפל!', readySub: '100 תרגילים קטנים. אתגר אחד גדול.', noRush: 'בלי לחץ. בקצב שלכם.', numbers: 'מספרים מ־1 עד 10', progressTitle: 'הדרך שלכם לאליפות', progressSub: 'כל תשובה נכונה מדליקה משבצת', solved: 'תרגילים פתרתם', outOf: 'מתוך 100', firstStep: 'המשבצת הראשונה מחכה לכם!', nextMilestone: 'היעד הבא', milestone: 'תרגילים',
    howTitle: 'איך משחקים?', step1: 'מקבלים תרגיל בהפתעה', step1Sub: 'בכל פעם תרגיל אחד חדש.', step2: 'כותבים את התשובה', step2Sub: 'טעיתם? מנסים שוב. הכול בסדר.', step3: 'מאירים את כל הלוח', step3Sub: 'יותר תשובות, פחות זמן — יותר גבוה בדירוג!',
    viewBoard: 'ללוח האלופים', practiceOnly: 'בינתיים מתאמנים! התחרות המשותפת תיפתח בקרוב.', offline: 'אין חיבור לאינטרנט. אפשר לשחק בתרגול.', onlineLost: 'החיבור נקטע. התחברו כדי להמשיך — השעון ממשיך לרוץ.', onlineBack: 'חזרנו! אפשר להמשיך.',
    hi: 'איזה כיף,', question: 'תרגיל', time: 'הזמן שלכם', answer: 'התשובה שלך', check: 'בדיקה', erase: 'מחיקת ספרה', correct: 'בול! ממשיכים לתרגיל הבא', incorrect: 'עוד ניסיון קטן, אתם יכולים!', typeAnswer: 'כותבים תשובה ואז בודקים', finish: 'סיום ושמירה', finishPractice: 'סיום תרגול', finishTitle: 'מסיימים להיום?', finishText: 'מה שפתרתם כבר נחשב! נשמור את הניסיון בלוח האלופים. השעון ממשיך עד לסיום.', finishPracticeText: 'אפשר לסיים עכשיו או להמשיך ולהאיר עוד משבצות.', continue: 'ממשיכים לשחק', confirmFinish: 'כן, לסיים',
    resultFull: 'כל הלוח שלכם!', resultPartial: 'כל הכבוד על הדרך!', resultSub: 'עוד תרגול, עוד ביטחון. כל תשובה היא התקדמות.', saved: 'הניסיון שלכם נשמר בלוח האלופים', practiceResult: 'זה היה תרגול — התוצאה לא נשלחה לתחרות.', again: 'משחק חדש', resume: 'ממשיכים מאיפה שעצרתם', resumeSub: 'המשחק שלכם מחכה לכם. במשחק תחרות השעון ממשיך גם כשאתם יוצאים.', resumeButton: 'חזרה למשחק', discard: 'סיום המשחק הקודם',
    boardTitle: 'כל ניסיון הוא ניצחון.', boardSubtitle: 'יותר תרגילים נכונים קודמים. בשוויון — הזמן הקצר מנצח.', rank: 'מקום', player: 'שם', score: 'פתרו', date: 'תאריך', noScores: 'מי יהיו האלופים הראשונים?', noScoresSub: 'מסיימים משחק תחרות, והניסיון מופיע כאן.', boardNotReady: 'לוח האלופים ייפתח בקרוב', boardNotReadySub: 'בינתיים אפשר לתרגל ולהגיע לתחרות מוכנים.', refresh: 'רענון', loadMore: 'עוד ניסיונות', loading: 'רק רגע…', networkError: 'לא הצלחנו להתחבר. נסו שוב — ההתקדמות שלכם נשמרה.', missingGame: 'המשחק הזה כבר לא זמין. אפשר להתחיל משחק חדש.', retry: 'ניסיון נוסף', emptyName: 'רק שם קטן, ויוצאים לדרך!',
    install: 'התקנת המשחק', installTitle: 'המשחק תמיד בהישג יד', installText: 'באייפון או באייפד: פותחים ב־Safari, לוחצים על שיתוף ואז ״הוספה למסך הבית״. באנדרואיד ובמחשב: בוחרים ״התקנת אפליקציה״ בתפריט הדפדפן.', close: 'סגירה', footer: 'קצת סקרנות. הרבה כפל.', admin: 'כניסת הורים ומורים', adminTitle: 'ניהול לוח האלופים', email: 'אימייל', password: 'סיסמה', login: 'כניסה', logout: 'יציאה', adminSetup: 'ניהול התחרות יהיה זמין אחרי חיבור לוח האלופים.', adminDenied: 'לחשבון הזה אין הרשאת ניהול.', loginError: 'הכניסה לא הצליחה. בדקו את האימייל והסיסמה.', remove: 'מחיקה', clearAll: 'איפוס התחרות', deleteTitle: 'למחוק את הניסיון הזה?', deleteText: 'הניסיון יוסר מלוח האלופים. אי אפשר לבטל את המחיקה.', clearTitle: 'לאפס את כל התחרות?', clearText: 'כל התוצאות והמשחקים הפעילים יימחקו. פעולה זו אינה ניתנת לביטול.', cancel: 'ביטול', soundOn: 'כיבוי צלילים', soundOff: 'הפעלת צלילים', savedLocally: 'התרגול נשמר במכשיר הזה', yourProgress: 'ההתקדמות שלך', complete: 'מושלם!', installDone: 'המשחק מותקן',
  },
  en: {
    brand: 'Multiply Club', club: 'Small steps. Big brainpower.', play: 'Let’s play', board: 'Leaderboard', language: 'עברית',
    eyebrow: 'One question. One little win.', title1: 'Big things start', title2: 'with a little ×.', intro: 'A whole multiplication table. You’ve got this!',
    nameLabel: 'What’s your name?', namePlaceholder: 'Your name or nickname', nameHint: 'This name goes on the leaderboard. A nickname is great!', start: 'Let’s do this!', practice: 'Just practicing', practiceMode: 'Practice mode', competition: 'Competition',
    ready: 'Ready, set… multiply!', readySub: '100 little questions. One big adventure.', noRush: 'No rush. Find your rhythm.', numbers: 'Numbers from 1 to 10', progressTitle: 'Your path to 100', progressSub: 'Each right answer lights up a square', solved: 'questions solved', outOf: 'out of 100', firstStep: 'Your first little win is waiting!', nextMilestone: 'Next little goal', milestone: 'questions',
    howTitle: 'Here’s how it works', step1: 'Meet a surprise question', step1Sub: 'Just one new question at a time.', step2: 'Give it your best answer', step2Sub: 'Not quite right? Have another go.', step3: 'Light up the whole board', step3Sub: 'More answers, less time. Up you go!',
    viewBoard: 'See the leaderboard', practiceOnly: 'Practice is open! Our shared competition is coming soon.', offline: 'You’re offline. Practice is ready to play.', onlineLost: 'Connection lost. Reconnect to continue — the clock keeps running.', onlineBack: 'You’re back online. Let’s keep going!',
    hi: 'You’ve got this,', question: 'Question', time: 'Your time', answer: 'Your answer', check: 'Check', erase: 'Delete a digit', correct: 'You got it! Here comes the next one', incorrect: 'Not quite. Give it another go!', typeAnswer: 'Type your answer, then check', finish: 'Finish & save', finishPractice: 'Finish practice', finishTitle: 'Calling it a day?', finishText: 'Every answer counts! We’ll save this attempt to the leaderboard. The clock keeps running until you finish.', finishPracticeText: 'Finish now, or keep going and light up a few more squares.', continue: 'Keep playing', confirmFinish: 'Yes, finish',
    resultFull: 'One hundred little wins!', resultPartial: 'Look how far you’ve come!', resultSub: 'A little practice, a little more confidence. Every answer counts.', saved: 'Your attempt is on the leaderboard', practiceResult: 'This was practice. Your score wasn’t sent to the competition.', again: 'Play again', resume: 'Pick up where you left off', resumeSub: 'Your game is waiting. In a competition, the clock keeps running while you’re away.', resumeButton: 'Back to my game', discard: 'Finish previous game',
    boardTitle: 'Every try deserves a cheer.', boardSubtitle: 'Most correct answers first. Same score? The quicker time wins.', rank: 'Rank', player: 'Name', score: 'Solved', date: 'Date', noScores: 'Who will be our first champion?', noScoresSub: 'Finish a competition game to see your attempt here.', boardNotReady: 'A little competition is coming', boardNotReadySub: 'For now, get a head start with a little practice.', refresh: 'Refresh', loadMore: 'More attempts', loading: 'Just a moment…', networkError: 'We couldn’t connect. Try again — your progress is safe.', missingGame: 'This game is no longer available. You can start a new one.', retry: 'Try again', emptyName: 'One little name, and you’re ready to go!',
    install: 'Install game', installTitle: 'Keep a little learning handy', installText: 'On iPhone or iPad: open in Safari, tap Share, then Add to Home Screen. On Android or a computer: choose Install app in your browser menu.', close: 'Close', footer: 'A little curiosity. A lot of possibility.', admin: 'For parents & teachers', adminTitle: 'Manage leaderboard', email: 'Email', password: 'Password', login: 'Sign in', logout: 'Sign out', adminSetup: 'Competition management will be available once the shared leaderboard is connected.', adminDenied: 'This account doesn’t have administrator access.', loginError: 'Sign-in failed. Check your email and password.', remove: 'Delete', clearAll: 'Reset competition', deleteTitle: 'Delete this attempt?', deleteText: 'This attempt will be removed from the leaderboard. This cannot be undone.', clearTitle: 'Reset the whole competition?', clearText: 'All results and active games will be deleted. This cannot be undone.', cancel: 'Cancel', soundOn: 'Turn sounds off', soundOff: 'Turn sounds on', savedLocally: 'Practice saved on this device', yourProgress: 'Your progress', complete: 'All done!', installDone: 'Game installed',
  },
} as const
export type Copy = { [K in keyof typeof messages.en]: string }
